# Change these first
owner: bolyachevets # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Geomark
    url: https://apps.gov.bc.ca/pub/geomark/overview
    owner: bcgov-dss
    repo: geomark
  - name: Test Broken Site
    url: https://hello-world-nginx-fe64f4-dev.apps.silver.devops.gov.bc.ca
    owner: bcgov-dss
    repo: geomark

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Registry and Online Services Uptime Monitor"
  introMessage: You can check uptime status of our services and track incident resolutions
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
