name: Update Template CI
on:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
    types: [update_template]
  workflow_dispatch:
jobs:
  release:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Update template
        uses: bolyachevets/uptime-monitor@v1.28.0
        with:
          command: "update-template"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
